# Generated by Django 3.0.3 on 2020-08-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200814_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_site',
            new_name='portfolio_site',
        ),
    ]
